#!/usr/bin/python
#
# -*- coding: utf-8 -*-
#
################################################################################
#
#
#  @File name  : md2html.py
#
#  @Author     : xiong-kaifang   Version: v1.0   Date: 2016-05-24
#
#  @Description: The script to convert Markdwon text file to html.
#
#
#  @History    : Review history
#
#	<author>	    <time>	     <version>	    <desc>
#  xiong-kaifang   2016-05-24     v1.0          Rewrite this script.
#
################################################################################

import os
import sys
import time
import traceback

from   xml.dom.minidom import parse
import xml.dom.minidom
from   string import Template

def handleMarkdown(cmd):
    ret = os.popen(cmd);
    txt = ret.read();
    ret.close();
    return txt;

# Html template.

html_header_template = Template("""<!-- [TOCTYPE html]
    This file is automatically generated on ${generation_time}
    DO NOT modify this file!
-->

<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>${html_title}</title>
</head>

<body>

"""
)

html_tailer_template = Template("""
</body>
</html>

<!-- [TOCTYPE html]
    This file is automatically generated on ${generation_time}
    DO NOT modify this file!
-->
"""
)

mdfile_path = os.path.abspath(sys.argv[2]);

mdfile_dirt = os.path.split(mdfile_path)[0];

mdfile_name = os.path.basename(mdfile_path);

md_cmd_string = "{0} --html4tag {1}";

#html = handleMarkdown(md_cmd_string.format(mdfile_name))

html = open(mdfile_dirt + "/" + mdfile_name.split('.')[0] + ".html", "w");

html.write(html_header_template.substitute(html_title      = mdfile_name.split('.')[0],
                                           generation_time =
                                           time.ctime(time.time())));
#print html;
html.write(handleMarkdown(md_cmd_string.format(os.path.abspath(sys.argv[1]), mdfile_path)));
html.write(html_tailer_template.substitute(generation_time =
            time.ctime(time.time())));

html.close();
